[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1"
anyhow = "1"
indoc = "2"
lazy_static = "1"
once_cell = "1"
rayon = "1"
regex = "1"
