[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1"
atoi = "2"
lazy_static = "1"
once_cell = "1"
rayon = "1"
regex = "1"

[dev-dependencies]
anyhow = "1"
indoc = "2"
pretty_assertions = "1"
